version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: arnoallen
      MYSQL_DATABASE: inventory
    ports:
      - "3307:3306"
    volumes:
      - ./backend/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  frontend:
    build: ./frontend
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
